-- Delete existing sample data if any
DELETE FROM materials;

-- Insert real data from CSV
INSERT INTO materials (id, name, category, stock, unit) VALUES
('AC-ADSS-SM-12C', 'Aerial Cable Fiber Optik Single Mode 12 Core G.652 C Type ADSS Cable', 'Aerial Cable', 0, 'meter'),
('AC-ADSS-SM-24C', 'Aerial Cable Fiber Optik Single Mode 24 Core G.652 C Type ADSS Cable', 'Aerial Cable', 0, 'meter'),
('AC-ADSS-SM-48C', 'Aerial Cable Fiber Optik Single Mode 48 Core G.652 C Type ADSS Cable', 'Aerial Cable', 0, 'meter'),
('AC-ADSS-SM-96C', 'Aerial Cable Fiber Optik Single Mode 96 Core G.652 C Type ADSS Cable', 'Aerial Cable', 0, 'meter'),
('AC-ADSS-SM-144C', 'Aerial Cable Fiber Optik Single Mode 144 Core G.652 C Type ADSS Cable', 'Aerial Cable', 0, 'meter'),
('AC-ADSS-SM-288C', 'Aerial Cable Fiber Optik Single Mode 288 Core G.652 C Type ADSS Cable', 'Aerial Cable', 0, 'meter'),
('JC-OF-SM-12C', 'Joint Closure Untuk Fiber Optik Kapasitas 12 Core', 'Joint Closure', 0, 'pcs'),
('JC-OF-SM-24C', 'Joint Closure Untuk Fiber Optik Kapasitas 24 Core', 'Joint Closure', 0, 'pcs'),
('JC-OF-SM-48C', 'Joint Closure Untuk Fiber Optik Kapasitas 48 Core', 'Joint Closure', 0, 'pcs'),
('JC-OF-SM-96C', 'Joint Closure Untuk Fiber Optik Kapasitas 96 Core', 'Joint Closure', 0, 'pcs'),
('JC-OF-SM-144C', 'Joint Closure Untuk Fiber Optik Kapasitas 144 Core', 'Joint Closure', 0, 'pcs'),
('JC-OF-SM-288C', 'Joint Closure Untuk Fiber Optik Kapasitas 288 Core', 'Joint Closure', 0, 'pcs'),
('OTB-SM-6', 'OTB Single Mode kapasitas 12 core', 'OTB', 0, 'pcs'),
('OTB-SM-12', 'OTB Single Mode kapasitas 12 core', 'OTB', 0, 'pcs'),
('OTB-SM-24', 'OTB Single Mode kapasitas 24 core', 'OTB', 0, 'pcs'),
('OTB-SM-48', 'OTB Single Mode kapasitas 48 core', 'OTB', 0, 'pcs'),
('OTB-SM-96', 'OTB Single Mode kapasitas 96 core', 'OTB', 0, 'pcs'),
('OTB-SM-144', 'OTB Single Mode kapasitas 144 core', 'OTB', 0, 'pcs'),
('OTB-SM-288', 'OTB Single Mode kapasitas 288 core', 'OTB', 0, 'pcs'),
('PS-1-2-FDT', 'Passive Splitter 1:2 modular SC/UPC for FDT', 'Splitter', 0, 'pcs'),
('PS-1-4-FDT', 'Passive Splitter 1:4 modular SC/UPC for FDT', 'Splitter', 0, 'pcs'),
('PS-1-8-FAT', 'Passive Splitter 1:8 modular SC/UPC for FAT', 'Splitter', 0, 'pcs'),
('PS-1-16-FAT', 'Passive Splitter 1:16 modular SC/UPC for FAT', 'Splitter', 0, 'pcs'),
('FAT-PB-8C-SOLID', 'FAT type POLE Kap 8 core adaptor SC/UPC (incl Splitter 1:8)', 'FAT', 0, 'pcs'),
('FAT-PB-16C-SOLID', 'FAT type POLE Kap 16 core adaptor SC/UPC (incl 2 Splitter 1:8)', 'FAT', 0, 'pcs'),
('FDT-POLE-48C', 'FDT-Pole (Outdoor) Adaptor SC Kapasitas 48 Core', 'FDT', 0, 'pcs'),
('FDT-POLE-96C', 'FDT-Pole (Outdoor) Adaptor SC Kapasitas 96 Core', 'FDT', 0, 'pcs'),
('FDT-STDG-96C', 'Kabinet FDT(Outdoor) Adaptor SC Kapasitas 96 Core', 'FDT', 0, 'pcs'),
('FDT-STDG-144C', 'Kabinet FDT(Outdoor) Adaptor SC Kapasitas 144 Core', 'FDT', 0, 'pcs'),
('FDT-STDG-288C', 'Kabinet FDT(Outdoor) Adaptor SC Kapasitas 288 Core', 'FDT', 0, 'pcs'),
('NP-6.0-100-1S', 'New Pole 6 Meter 2,5 inch (100 Kg)', 'Pole', 0, 'pcs'),
('NP-7.0-140-2S', 'New Pole 7 Meter (140 Kg)', 'Pole', 0, 'pcs'),
('NP-7.0-140-3S', 'New Pole 7 Meter (140 Kg - Heavy)', 'Pole', 0, 'pcs'),
('NP-9.0-140-3S', 'New Pole 9 Meter (140 Kg)', 'Pole', 0, 'pcs'),
('NP-CB-7.0-250', 'New Pole Beton 7 Meter (250 Kg)', 'Pole', 0, 'pcs'),
('NP-CB-9.0-250', 'New Pole Beton 9 Meter (250 Kg)', 'Pole', 0, 'pcs'),
('PP-CD-IN', 'Pipe Protection Indoor Cable (Pvc White) 20 Mm', 'Protection', 0, 'meter'),
('PP-CD-OUT', 'Pipe Protection Outdoor Cable (Pvc Black) 20 Mm', 'Protection', 0, 'meter'),
('HDPE-40-33', 'Pipa Hdpe 40/33 Mm', 'Pipe', 0, 'meter'),
('TT-NP', 'Temberang Tarik', 'Accessories', 0, 'pcs'),
('ACC-STAINLESS BELT', 'Aksesoris Tiang Besi Stainless Belt dan Pengunci', 'Accessories', 0, 'pcs'),
('ACC-SUSPENSION AYUN', 'Aksesoris Tiang Besi Suspension Ayun', 'Accessories', 0, 'pcs'),
('ACC-HELLICAL', 'Aksesoris Tiang Besi Helycal Cable', 'Accessories', 0, 'pcs'),
('ACC-ANCHORING', 'Aksesoris Tiang Besi Penguat Fiber Optik Figure-8', 'Accessories', 0, 'pcs'),
('ACC-Bracket', 'Aksesoris Tiang Besi Anchoring/ Bracket A', 'Accessories', 0, 'pcs');
