-- Create Materials Table
CREATE TABLE materials (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    stock NUMERIC DEFAULT 0,
    unit TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Transactions Table
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id TEXT REFERENCES materials(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('in', 'out')),
    quantity NUMERIC NOT NULL,
    person TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) - For demo, we can set to public or simple auth
-- To keep it simple for now, we allow all access (suggesting to add Auth later)
ALTER TABLE materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON materials FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON materials FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON materials FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON materials FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON transactions FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON transactions FOR UPDATE USING (true);

-- Insert Sample Data
INSERT INTO materials (id, name, category, stock, unit) VALUES
('CBL-001', 'Fiber Cable 24 Core', 'Cable', 500, 'Meters'),
('CBL-002', 'Fiber Cable 48 Core', 'Cable', 250, 'Meters'),
('MCH-001', 'Splicer Machine Fusion', 'Equipment', 5, 'Pcs');
